# Generated by Django 3.2.4 on 2021-07-29 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('priority', models.IntegerField(choices=[(0, 'بی اهمیت'), (1, 'کم اهمیت'), (2, 'توجه'), (3, 'قابل توجه'), (4, 'مهم'), (5, 'ضروری')], default=4)),
                ('status', models.CharField(choices=[('disable', 'غیرفعال'), ('enable', 'فعال'), ('doing', 'در حال انجام'), ('done', 'انجام شده'), ('expire', 'منقضی'), ('archive', 'ارشیو'), ('unknown', 'بی سرپرست')], default='enable', max_length=10)),
                ('due_date', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(related_name='categories_item', to='todo.Categories')),
            ],
            options={
                'ordering': ('-due_date',),
            },
        ),
    ]
